server:
  port: 9090
spring:
  application:
    name: blog-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: ${spring.application.name}
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-ucenter
          uri: lb://service-ucenter
          predicates:
            - Path=/ucenter/**
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/oss/**
        - id: service-article
          uri: lb://service-article
          predicates:
            - Path=/article/**
        - id: service-comment
          uri: lb://service-comment
          predicates:
            - Path=/comment/**

